version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

  mock-users:
    build:
      context: ./mock-users
      dockerfile: Dockerfile  # Указываем Dockerfile напрямую
    container_name: mock-users
    ports:
      - "9100:9100"
    environment:
      - CONCURRENCY=100
      - DURATION=600
      - WAVES=5
      - INTERVAL=5
    restart: unless-stopped
    depends_on:
      - prometheus

volumes:
  grafana-storage:
